### ISSUE TITLE
Bản đồ - Chưa có bản đồ hiển thị, hình ảnh attach là khi ở phần map rồi vào phân hệ quản lý người dùng

### ISSUE THREAD

**Issue by antt** [VidaGIS/870#12]
![870](https://cloud.githubusercontent.com/assets/19400596/15568056/1bc700ae-2354-11e6-9c2d-6e6d4fca5f14.png)

**Comment by quangtrung4695** [comment]
đã sửa lỗi, anh Ân test lại nhé
