### ISSUE TITLE
Danh mục viễn thông_ Tìm kiếm loại trạm BTS

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#18]
Không Thực hiện tìm kiếm trạm BTS được khi chỉ nhập thông tin trường Mô tả, trường mã và tên bỏ trống
Lỗi xảy ra tương tự với danh mục khác trong danh mục viễn thông và danh mục bưu chính

**Comment by duongngocthanh** [comment]
Đã có tìm kiếm với thông tin của trường mô tả
