### ISSUE TITLE
Danh mục viễn thông_ Tìm kiếm loại trạm BTS

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#19]
Vẫn thực hiện tìm kiếm trạm BTS được khi: 
1. Điền thông tin trường Mã và tên đúng, mô tả không tồn tại hoặc
2. Điền thông tin trường Mã và mô tả đúng, tên không tồn tại
Lỗi xảy ra tương tự với danh mục khác trong danh mục viễn thông và danh mục bưu chính!

**Comment by duongngocthanh** [comment]
Mô tả không rõ bug

**Comment by LeQuynh** [comment]
Đã fix
