### ISSUE TITLE
Danh mục viễn thông_ Thêm mới loại trạm BTS

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#20]
Vẫn thực hiện thêm mới loại trạm BTS thành công khi:
1. Mã chứa khoảng trắng, ký tự đặc biệt, thẻ html, câu lệnh SQL
2. Trường mã lớn hơn 30 ký tự
Các danh mục khác của danh mục viễn thông và danh mục bưu chính cũng bị lỗi tương tự.

**Comment by duongngocthanh** [comment]
Đã fix xong
