### ISSUE TITLE
Danh mục viễn thông_ Edit  loại trạm BTS

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#21]
Vẫn báo update thành công khi thực hiện sửa loại trạm BTS trường hợp:
1. Mã chứa khoảng trắng, ký tự đặc biệt, thẻ html, câu lệnh SQL
2. Trường mã lớn hơn 30 ký tự
Các danh mục khác của danh mục viễn thông và danh mục bưu chính cũng bị lỗi tương tự.

**Comment by VidaGIS** [comment]
Thanh fix rồi, Quỳnh test lại nhé
