### ISSUE TITLE
Danh mục hệ thống_Loại phân hệ

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#23]
Khi đã kết thúc thêm mới, chuyển sang thực hiện tìm kiếm mà vẫn hiển thị thông báo "Bạn chưa chọn loại phân hệ!"

![erro1](https://cloud.githubusercontent.com/assets/19704107/16146349/c0e72fe6-34a7-11e6-8414-c6b51bca2da1.PNG)

Khi đã edit thành công, chuyển sang thực hiện tìm kiếm mà vẫn hiển thị thông báo "Bạn chưa chọn loại phân hệ!"

![error2](https://cloud.githubusercontent.com/assets/19704107/16146524/a6008686-34a8-11e6-9009-0e7f893686a0.PNG)

**Comment by duongngocthanh** [comment]
Đã fix bug này

**Comment by LeQuynh** [comment]
Đã ok
