### ISSUE TITLE
Quản lý đối tượng_ Thêm mới điểm thuộc tính

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#24]
Trong form thêm mới điểm thuộc tính trạm BTS.
1. Thay "Mã loại trạm" bằng "Loại trạm"
2. Thay "Mã giấy tiêu chuẩn kiểm định" bằng "Giấy tiêu chuẩn kiểm định :"
3. Phần "Danh sách giấy phép xây dựng" trong bảng "Quản lý đối tượng" thay "Mã loại tài liệu" thành "Loại tài liệu"

**Comment by quangtrung4695** [comment]
đã fix lỗi, chị Quỳnh kiểm tra lại nhé

**Comment by LeQuynh** [comment]
Đã ok
