### ISSUE TITLE
Quản lý người dùng_Thêm mới tài khoản

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#26]
Khi tạo mới tài khoản cấp tỉnh hoặc huyện. 
Trong form thêm mới tài khoản: phần lớp tài sản không được tích chọn (Ví dụ không tích chọn lớp BTS) 
Nhưng sau khi đã thêm mới thành công, ta đăng nhập lại với tài khoản đó vẫn truy vấn được trạm BTS.

**Comment by quangtrung4695** [comment]
chị test lại lỗi này xem xảy ra được lỗi này ko nhé
