### ISSUE TITLE
Quản lý đối tượng_ Thêm mới điểm thuộc tính

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#27]
Khi thêm mới trạm BTS. Trường hợp không chọn loại trạm thì Hiển thị thông báo lỗi "Trường Mã loại trạm phải có dữ liệu" 
=> Phải sửa lại là  "Trường Loại trạm phải có dữ liệu"

**Comment by quangtrung4695** [comment]
đã fix lỗi

**Comment by LeQuynh** [comment]
Đã ok
