### ISSUE TITLE
Quản lý đối tượng_Thêm mới trạm BTS/Danh sách phát sóng

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#28]
Trong form Danh sách phát sóng, trường hợp không chọn "Thiết bị thu phát", và "Nhà mạng sử dụng BTS" 
thì hệ thống hiển thị thông báo "Trường mã thiết bị thu phát phải có dữ liệu" và " Trường mã nhà mạng sử dụng BTS phải có dữ liệu".
**=>** Sửa lại thông báo thành
"Trường thiết bị thu phát phải có dữ liệu" và " Trường nhà mạng sử dụng BTS phải có dữ liệu".

**Comment by quangtrung4695** [comment]
đã fixed

**Comment by LeQuynh** [comment]
Đã ok
