### ISSUE TITLE
Danh mục viễn thông _Nhà mạng

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#29]
Sửa tên "Nhà mạng" **=>** "Doanh nghiệp"
Vì bên thêm mới user, là chọn doanh nghiệp chứ không phải chọn nhà mạng.

**Comment by duongngocthanh** [comment]
Bên thêm mới user là chọn nhà mạng. Chứ không phải chọn doanh nghiệp. Đã sửa thành chọn nhà mạng
