### ISSUE TITLE
Quản lý điểm thuộc tính_Phê duyệt

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#30]
1. Form Phê duyệt ->Thay đổi icon "Xem thông tin" trong form phê duyệt
2. Chức năng tìm kiếm trong form phê duyệt bị lỗi.
3. Chức năng phê duyệt trong form Phê duyệt
- Bỏ trường "Mã giấy tiêu chuẩn kiểm định"
- Hiển thị thêm trường "Lý do" nếu không phê duyệt
4. Trong trường hợp người dùng thực hiện edit. Các điểm chưa được phê duyệt phải hiển thị lý do
5. Nếu thực hiện chọn "Xem thông tin" trong form phê duyệt trước, sau đó chọn chức năng phê duyệt thì form danh sách phát sóng bị lỗi hiển thị khi click chọn "xem thêm"
![a](https://cloud.githubusercontent.com/assets/19704107/16911163/158538dc-4d07-11e6-88c2-eece32c4cf61.PNG)

**Comment by quangtrung4695** [comment]
đã fix lỗi chút em gửi bản war mới rồi kiểm tra lại nhé
