### ISSUE TITLE
Quản lý đối tượng_Thêm điểm thuộc tính BTS

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#32]
Lỗi trong form "Danh sách giấy phép xây dựng"
![a1](https://cloud.githubusercontent.com/assets/19704107/16973017/1983eace-4e5a-11e6-9948-83d5a9d527b7.png)

**Comment by quangtrung4695** [comment]
đã fix lỗi, bản war sau chị test lại nhé

**Comment by LeQuynh** [comment]
Tại sao bây giờ lại không thêm mới được vậy Trung?
