### ISSUE TITLE
Quản lý điểm thuộc tính_Nhập thông tin thuộc tính qua tệp

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#33]
Chọn lớp tài sản là BTS -> Chọn "Nhập thông tin thuộc tính qua tệp"
Mặc dù báo thành công nhưng vẫn bị lỗi.

![a](https://cloud.githubusercontent.com/assets/19704107/17019740/14bfadc0-4f68-11e6-810d-e3a8136a417f.png)

**Comment by quangtrung4695** [comment]
đã fix chị chờ bản war mới để test lại nhé
