### ISSUE TITLE
Truy vấn đối tượng_Truy vấn thuộc tính

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#38]
Một số lỗi phần truy vấn thuộc tính đối tượng. File đính kèm bên dưới.
[Issue870.4.8.2016.docx](https://github.com/VidaGIS/870/files/403541/Issue870.4.8.2016.docx)

**Comment by duongngocthanh** [comment]
Đã fix phần lỗi do code, còn phần hiển thị tên trường là sau này do người dùng có thể đổi tên trong phần quản lý hệ thống.
