### ISSUE TITLE
Quản lý điểm thuộc tính_Thêm mới đối tượng

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#39]
1. Sửa lỗi chính tả cho các đối tượng tài sản: Viết hoa chữ cái đầu dòng cho từng đối tượng tài sản
2. Thay tên "Cập nhập điểm thuộc tính" thành "Cập nhật tài sản", "Thêm điểm thuộc tính" thành "Thêm tài sản", "Xóa điểm thuộc tính" thành "Xóa tài sản"

![image](https://cloud.githubusercontent.com/assets/19704107/17729359/135eca66-648e-11e6-875f-0afb62a6338b.png)
1. Đổi tiêu đề cho các form thêm mới thành "Thêm mới điểm tài sản"
2. Lỗi thêm mới của các đối tượng tài sản: Bưu cục, Cột treo cáp, dịch vụ viễn thông, trạm viba, truyền thanh cơ sở, internet không dây, truyền hình cáp, trạm viễn thông, vô tuyến điện.
   [issue.870.Themdiemthuoctinh.docx](https://github.com/VidaGIS/870/files/422045/issue.870.Themdiemthuoctinh.docx)

**Comment by quangtrung4695** [comment]
đã fix, chị chờ bản war mới nhé
