### ISSUE TITLE
Quản lý đối tượng _Thêm mới tài sản

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#40]
Danh sách issue thêm mới tài sản của các đối tượng: Trạm BTS, Đại lý internet, Cột ăng ten, Thùng thư độc lập, Bưu điện văn hóa.
[issue.870.Themdiemthuoctinh.docx](https://github.com/VidaGIS/870/files/424155/issue.870.Themdiemthuoctinh.docx)

**Comment by quangtrung4695** [comment]
em đã fix, chị chờ bản war mới để test lại nhé

**Comment by LeQuynh** [comment]
Chưa đạt yêu cầu nhé!
1. Lỗi trường bắt buộc 
2. Lỗi form "Danh sách phát sóng chưa sửa
.......Hình như e chưa sửa sao ấy :D
