### ISSUE TITLE
Các tài sản chưa hiển thị identify 

### ISSUE THREAD

**Issue by antt** [VidaGIS/870#44]
Trạm viba
Trạm viễn thông
Truyền thanh cơ sở - Bỏ "Mã" Mã số giấy phép
Truyền thanh cơ sở
Tuyến truyền dẫn - Bỏ "Mã" Mã phương thức kết nối
Tuyến truyền dẫn

**Comment by VidaGIS** [comment]
do service geoserver
Phương sẽ fix
