### ISSUE TITLE
Quản lý đối tượng_ Thêm mới tài sản

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#45]
1.  Báo lỗi trường bắt buộc nhập cho các trường bắt buộc 
2. Sửa lại chính tả cho các trường
3. Sửa lại  sao cho các trường trong form hiển thị cân đối: Các trường input bằng các dropdownlist chọn thông tin
   .....
   Chi tiết ( Đây là 1 số điểm, các điểm còn lại tương tự)
   [issue870.14.10.2016.docx](https://github.com/VidaGIS/870/files/543980/issue870.14.10.2016.docx)

**Comment by quangtrung4695** [comment]
ok
