### ISSUE TITLE
Truy vấn đối tượng/Truy vấn không gian/Tài sản trong bán kính

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#46]
1. Từ đối tượng thùng thư độc lập thì nút Phóng tới không hoạt động
2. Chuyển sang đối tượng khác phải load lại page
3. Thi thoảng bị treo máy chỉ thực hiện chấm được ở 1 điểm di chuyển chấm điểm khác không được hoặc chấm được nhưng chấm 1 chỗ khoanh vùng 1 chỗ 
4. Không tìm kiếm được cho tài sản dạng đường

**Comment by quangtrung4695** [comment]
1. đã fix
2. em chưa hiểu rõ lỗi này lắm
3. đã hướng dẫn lại phần này
4. chưa fix
