### ISSUE TITLE
Công cụ hỗ trợ

### ISSUE THREAD

**Issue by antt** [VidaGIS/870#53]
- Ẩn chức năng "Thông tin thuộc tính"
- Chức năng "Hiển thị nhãn" không chạy được trong cả 2 trình duyệt
 + bị vỡ phông chữ - khung trong trình duyệt firefox
 + Không thể có scrollbar trong trình duyệt chorme

**Comment by quangtrung4695** [comment]
đã ẩn 1 số chức năng .
