### ISSUE TITLE
Chức năng xác nhận

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#54]
1. Lỗi chính tả, chưa hiển thị lý do xác nhận
2. Hiển thị map cho chức năng xác nhận

**Comment by quangtrung4695** [comment]
1. đã fix được
2. Chưa làm ạ :D

**Comment by LeQuynh** [comment]
1. Chưa thấy hiển thị lý do không xác nhận
2. Sửa lỗi chính tả " Cơ quan quẩn lý cấp huyện"
3. Chưa sửa lại icon hiển thị chưa phê duyệt
