### ISSUE TITLE
Bản đồ chuyên đề

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#55]
1. Lối front chữ "Lưu lại thành công" khi tạo
2. Fix lại: Sau khi thêm mới bản đồ chuyên đề thành công thì tắt form "Bản đồ chuyên đề" đi
3. Chỉnh lại css form "Bản đồ chuyên đề"
4. Thêm sao đỏ trường bắt buộc cho trường "Lớp chuyên đề, trường chuyên đề, tên chuyên đề"
5. Fix "Tên chuyên đề" ko được trùng nhau

**Comment by quangtrung4695** [comment]
đã fix lỗi
