### ISSUE TITLE
Quản lý quy hoạch/Thêm mới quy hoạch

### ISSUE THREAD

**Issue by LeQuynh** [VidaGIS/870#59]
Lỗi ko cập nhật và chính tả, nút làm mới k hoạt động
![a](https://cloud.githubusercontent.com/assets/19704107/20334174/998262bc-abea-11e6-9fee-48afb967ac6b.png)

**Comment by quangtrung4695** [comment]
đã fix lỗi

**Comment by Quynhlta** [comment]
not ok. Nút làm mới vẫn chưa hoạt động

**Comment by quangtrung4695** [comment]
đã fix lại
