### ISSUE TITLE
Quản lý đối tượng/ Thêm tài sản qua nhập dữ liệu BTS

### ISSUE THREAD

**Issue by Quynhlta** [VidaGIS/870#65]
Vẫn báo lỗi khi nhập đúng tọa độ (khi login với tài khoản tỉnh)
![image](https://cloud.githubusercontent.com/assets/23545114/20417839/daf61464-ad7a-11e6-9e8c-9b2adef0bf26.png)

**Comment by quangtrung4695** [comment]
đã fix, chị chờ bản war mới nhé
