### ISSUE TITLE
Quản lý đối tượng/ Thêm tài sản qua nhập dữ liệu Đại lý internet

### ISSUE THREAD

**Issue by Quynhlta** [VidaGIS/870#67]
Đại lý internet và cột ăng ten thông báo lỗi "không lưu lại được"
![image](https://cloud.githubusercontent.com/assets/23545114/20421531/1e214d14-ad97-11e6-851c-eb6b3b7b05b5.png)

**Comment by quangtrung4695** [comment]
đã fix, chị chờ bản war mới nhé
