### ISSUE TITLE
Quản lý đối tượng/ Thêm mới đối tượng cột ăng ten

### ISSUE THREAD

**Issue by Quynhlta** [VidaGIS/870#68]
Sửa lại thông báo lỗi và thêm sao đỏ trường bắt buộc cho trường độ cao
![a](https://cloud.githubusercontent.com/assets/23545114/20423357/62caaf04-ada2-11e6-8e90-d18827a52cae.PNG)

**Comment by quangtrung4695** [comment]
đã fix, chị chờ bản war mới nhé

**Comment by Quynhlta** [comment]
Chưa có sao đỏ bắt buộc cho trường độ cao
