### ISSUE TITLE
Quản lý đối tượng/Thêm đối tượng qua nhập dữ liệu Đại lý internet

### ISSUE THREAD

**Issue by Quynhlta** [VidaGIS/870#70]
Thêm sao đỏ trường bắt buộc cho trường quận/huyện, phường/xã
![image](https://cloud.githubusercontent.com/assets/23545114/20587148/5abd702c-b23d-11e6-8987-47c0d2adc660.png)

**Comment by quangtrung4695** [comment]
đã fix
