### ISSUE TITLE
Xác nhận lên bản đồ

### ISSUE THREAD

**Issue by Quynhlta** [VidaGIS/870#71]
Lỗi front
![image](https://cloud.githubusercontent.com/assets/23545114/20619748/c94f9fb0-b328-11e6-90f7-551569a7ab3a.png)

![image](https://cloud.githubusercontent.com/assets/23545114/20619756/d89a3b42-b328-11e6-804e-eea657997c7d.png)

**Comment by quangtrung4695** [comment]
đã fix
